server:
  # ??? Web ??????????
  port: 9003
spring:
  application:
    # ?????
    name: dispatcher-service
  cloud:
    function:
      # ??? Spring Cloud Function ?????
      definition: pack|label
