server:
  # 嵌入式 Web 服务器将会用到的端口
  port: 9003
spring:
  application:
    # 应用的名称
    name: dispatcher-service
  config:
    # 如果配置服务器可用的话，会在这里导入配置数据
    import: "optional:configserver:"
  cloud:
    config:
      # 配置服务器的 URL
      uri: http://localhost:8888
      # 等待连接配置服务器的超时时间 (毫秒)
      request-connect-timeout: 5000
      # 等待从配置服务器读取配置数据的超时时间 (毫秒)
      request-read-timeout: 5000
      # 将连接至配置服务器的失败设置为致命错误
      fail-fast: true
      retry:
        # 最大的尝试次数
        max-attempts: 6
        # Backoff 的初始重试间隔 (毫秒)
        initial-interval: 1000
        # Backoff 的最大重试间隔 (毫秒)
        max-interval: 2000
        # 计算下一次间隔的乘数
        multiplier: 1.1
    function:
      # 定义由 Spring Cloud Function 管理的函数
      definition: pack|label
    stream:
      # 用于配置目的地绑定的区域
      bindings:
        # 输入绑定
        packlabel-in-0:
          # 在代理中，绑定器实际绑定的名称 (RabbitMQ 中的交换机)
          destination: order-accepted
          # 对目的地感兴趣的消费者组，与应用的名称相同
          group: ${spring.application.name}
        # 输出绑定
        packlabel-out-0:
          # 在代理中，绑定器实际绑定的名称 (RabbitMQ 中的交换机)
          destination: order-dispatched
  # 配置与 RabbitMQ 的集成
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
